<!-- eslint-disable vue/multi-word-component-names -->
<script setup lang="ts">
/**
 * Logo Component - Auto-generated by brand-apply
 * Icon Library: Lucide
 */
defineProps<{
  withText?: boolean
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl'
}>()

const sizes = {
  xs: { icon: 'w-6 h-6', text: 'text-sm', gap: 'gap-1.5' },
  sm: { icon: 'w-8 h-8', text: 'text-base', gap: 'gap-2' },
  md: { icon: 'w-10 h-10', text: 'text-lg', gap: 'gap-2.5' },
  lg: { icon: 'w-12 h-12', text: 'text-xl', gap: 'gap-3' },
  xl: { icon: 'w-16 h-16', text: 'text-2xl', gap: 'gap-4' }
}
</script>

<template>
  <div
    class="flex items-center"
    :class="sizes[size || 'md'].gap"
  >
    <UIcon
      name="i-lucide-leaf"
      class="shrink-0 text-primary"
      :class="sizes[size || 'md'].icon"
      style="transform: rotate(119deg);"
    />
    <span
      v-if="withText"
      class="font-bold text-[var(--ui-text-highlighted)]"
      :class="sizes[size || 'md'].text"
      style="font-family: 'Nunito', sans-serif;"
    >
      DeComer
    </span>
  </div>
</template>
